# Team Project

In [1]:
import pandas as pd

In [18]:
df_employees = pd.read_csv('../user_access_logs/employees.csv')
df_system_access = pd.read_csv('../user_access_logs/system_access.csv')
df_employees.set_index('employee_number', inplace=True)
df_employees = df_employees.set_index('last_name')
df = df_employees.join(df_system_access, how='left')
df.head(25)

,first_name,email,title,id,access_level
Abbate,Gweneth,gweneth.abbate@consultants.com,Director of Sales,NaN,NaN
Abbyss,Arthur,arthur.abbyss@consultants.com,Account Manager,NaN,NaN
Abdee,Beatrice,beatrice.abdee@consultants.com,Sales Assistant,NaN,NaN
Abels,Dyane,dyane.abels@consultants.com,Director of Sales,NaN,NaN
Aberdalgy,Christy,christy.aberdalgy@consultants.com,Sales Assistant,NaN,NaN
Abramowitch,Tades,tades.abramowitch@consultants.com,Account Manager,NaN,NaN
Adamiec,Hyacintha,hyacintha.adamiec@consultants.com,Director of Sales,NaN,NaN
Addington,Audi,audi.addington@consultants.com,Sales Assistant,NaN,NaN
Adenot,Rhett,rhett.adenot@consultants.com,Account Manager,NaN,NaN
Adkin,Prentiss,prentiss.adkin@consultants.com,Sales Assistant,NaN,NaN
Agius,Dahlia,dahlia.agius@consultants.com,Account Manager,NaN,NaN
Aingell,Carlota,carlota.aingell@consultants.com,Account Manager,NaN,NaN
Ainscow,Amber,amber.ainscow@consultants.com,Sales Assistant,NaN,NaN
Aird,Fanni,fanni.aird@consultants.com,Account Manager,NaN,NaN
Akast,Carson,carson.akast@consultants.com,Account Manager,NaN,NaN
Akitt,Ester,ester.akitt@consultants.com,Director of Sales,NaN,NaN
Alban,Lilas,lilas.alban@consultants.com,Account Manager,NaN,NaN
Aldam,Tymon,tymon.aldam@consultants.com,Sales Assistant,NaN,NaN
Aldcorn,Sherry,sherry.aldcorn@consultants.com,Sales Assistant,NaN,NaN
Alders,Vaclav,vaclav.alders@consultants.com,Account Manager,NaN,NaN
Aldin,Gayla,gayla.aldin@consultants.com,Director of Sales,NaN,NaN
Allaway,Pat,pat.allaway@consultants.com,Account Manager,NaN,NaN
Amery,Meggy,meggy.amery@consultants.com,Account Manager,NaN,NaN
Amsberger,Eleanora,eleanora.amsberger@consultants.com,Sales Assistant,NaN,NaN
Andrewartha,Hilton,hilton.andrewartha@consultants.com,Account Manager,NaN,NaN